### ISSUE TITLE
01.6 

### ISSUE THREAD

**Issue by ykhorkova** [4GeeksAcademy/react-exercises#10]
No result picture 
<img width="541" alt="screen shot 2018-10-23 at 5 09 31 pm" src="https://user-images.githubusercontent.com/38229847/47390909-79daba80-d6e6-11e8-8a1e-3f30de739de3.png">

**Comment by alesanchezr** [comment]
This is really simple to fix @ykhorkova, all the tutorial images are in the `/_assets/` folder and the path for the image has to be '/assets/image_name.png'.

Do you want to try and fix it?

**Comment by alesanchezr** [comment]
The image was being ignored on the gitignore. Now fixed :)
