### ISSUE TITLE
02.2

### ISSUE THREAD

**Issue by ykhorkova** [4GeeksAcademy/react-exercises#11]
Shows error when press TEST

<img width="883" alt="screen shot 2018-10-23 at 5 27 48 pm" src="https://user-images.githubusercontent.com/38229847/47391911-0d14ef80-d6e9-11e8-831b-b45adb4d8f37.png">

**Comment by alesanchezr** [comment]
the .gitignore was ignoring most of the files and the tests.js were not being included into the repo. Now it is fixed. 😄
