### ISSUE TITLE
ENHANCEMENT: Help Button to Show 4 Step Tutorial & Reminder to Deliver

### ISSUE THREAD

**Issue by vicks1008** [4GeeksAcademy/react-exercises#19]
### Reminder to Deliver
When I was completing my very first exercise `#01.1-hello-world` & I was satisfied with my code, I was quick to want to continue to the next step. My first attempt was to select the _Next_ link so I did. 

Little did I know I completely forgot step #4 of the tutorial that mentions to deliver your code using the command `$ bc deliver:exercises`.

It would be great if there was a reminder or some kind of validation when you don't type the command `$ bc deliver:exercises` for forgetful people like me. 😅

### Help Button to Show 4 Step Tutorial
As I was on exercise `#01.2-hello-jsx` I had a feeling something was missing or wrong from the previous exercise. It's as if pressing _Next_ to continue to the next exercise felt too easy! So naturally I selected the _Previous_ link to go back and check my code. 

This is when I noticed the 4 step tutorial showed up again. At first I wanted to report that as an issue but instead I am recommending an approach to maybe add some kind of question icon (maybe with HELP text) that when selected the 4 step tutorial shows up whenever you need help! 

I figured this would make sense since the container on the left and the split pane container on the right will remain the same for all exercises, the tutorial that highlights the containers should & makes sense to be seen from any exercise.

**Comment by alesanchezr** [comment]
U r right man, this is a great idea. I will put this on the pipeline.
