### ISSUE TITLE
File download:exercises is unavailable

### ISSUE THREAD

**Issue by idosius** [4GeeksAcademy/react-exercises#25]
When executing `bc download:exercises` I get the following message and the exercises don't download:
File download:exercises is unavailable.

I'm using MacOS Mojave.

**Comment by alesanchezr** [comment]
Hello @idosius what if you do `breathecode download:exercises` ?

You can also manually clone the repository and run the `bc run` command at the root of repository.

Let me know if that helps.

**Comment by idosius** [comment]
Works with `breathecode download:exercises`. The default bc comes from /usr/bin/bc and is [an arbitrary precision calculator language
](https://www.gnu.org/software/bc/manual/html_mono/bc.html)

Would be cool if you could update the installation instructions. Thanks for the help!
