### ISSUE TITLE
Review grammar and spelling

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/react-exercises#6]
1. The repository contains one `exercises` folder with each exercise inside in another folder.
2. Each exercise contains a `README.md` file with the instructions on how to solve it.
3. All the instructions need to be reviewed and correct any grammar or spelling issue.

How to do you Pull Request?
1. Fork the repository.
2. Clone it to your computer if you want to work locally.
2. Start the review process and edit all the README.md files you consider.
3. Commit all changes.
4. Push to your own repository.
5. Go to your repository in github a look for the push request button.

Here is more on how to do it (https://yangsu.github.io/pull-request-tutorial/)[https://yangsu.github.io/pull-request-tutorial/]

**Comment by LaimeJesus** [comment]
Hello, I'll be working on this
