### ISSUE TITLE
Result card in 01.4

### ISSUE THREAD

**Issue by ykhorkova** [4GeeksAcademy/react-exercises#9]
In the end of the task it is a result card.
But actually it is wrong card there, without all information from "const data"
Should be with Bob Dylan info

<img width="504" alt="screen shot 2018-10-23 at 4 30 20 pm" src="https://user-images.githubusercontent.com/38229847/47389062-c53e9a00-d6e1-11e8-941f-1204b977c8a8.png">

**Comment by alesanchezr** [comment]
Done!
